create table auth.bank_account
(
    id          integer primary key generated by default as identity,
    code        text                                                   not null unique,
    currency    text                                                   not null,
    status      text check (status in ('DELETE', 'ACTIVE', 'FREEZED')) not null,
    date_create timestamp(6) with time zone                            not null,
    user_id     integer                                                not null,
    foreign key (user_id) references auth.user (id)
        on delete cascade
);
CREATE INDEX idx_user_id ON auth.bank_account(user_id);--хотя он автоматический вроде
