create table auth.user
(
    id                    integer primary key generated by default as identity,
    login                 text                        not null unique,
    password              text                        not null,
    first_name            text                        not null,
    middle_name           text                        not null,
    last_name             text                        not null,
    mail                  text                        not null unique,
    is_staff              boolean                     not null,
    number_phone          text                        not null unique,
    status                text,
    date_create           timestamp(6) with time zone not null,
    date_update           timestamp(6) with time zone,
    user_loyalty_level_id integer                     not null,
    foreign key (user_loyalty_level_id) references auth.user_loyalty_level (id)
        on delete cascade
)
