create table auth.user_loyalty_level
(
    id        integer primary key generated by default as identity,
    title     text    not null,
    code      text    not null unique,
    is_active boolean not null

)